<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/

$relationships = array (
  'fs_fourniseur_modified_user' => 
  array (
    'id' => '6b9de44b-d794-d93a-523b-57b60de8ea28',
    'relationship_name' => 'fs_fourniseur_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'fs_fourniseur',
    'rhs_table' => 'fs_fourniseur',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'fs_fourniseur_created_by' => 
  array (
    'id' => '6c06e6df-c251-3086-70d1-57b60df4ea69',
    'relationship_name' => 'fs_fourniseur_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'fs_fourniseur',
    'rhs_table' => 'fs_fourniseur',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'fs_fourniseur_assigned_user' => 
  array (
    'id' => '6c35fcaf-d56b-0584-d824-57b60d898da4',
    'relationship_name' => 'fs_fourniseur_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'fs_fourniseur',
    'rhs_table' => 'fs_fourniseur',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'fs_fourniseur_aos_contracts_1' => 
  array (
    'id' => '906413bb-25ff-208a-a710-57b60d6bbed6',
    'relationship_name' => 'fs_fourniseur_aos_contracts_1',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'AOS_Contracts',
    'rhs_table' => 'aos_contracts',
    'rhs_key' => 'id',
    'join_table' => 'fs_fourniseur_aos_contracts_1_c',
    'join_key_lhs' => 'fs_fourniseur_aos_contracts_1fs_fourniseur_ida',
    'join_key_rhs' => 'fs_fourniseur_aos_contracts_1aos_contracts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fs_fourniseur_activities_1_notes' => 
  array (
    'id' => '916ebf37-f6c6-f845-0c60-57b60ddfa5ce',
    'relationship_name' => 'fs_fourniseur_activities_1_notes',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'fs_fourniseur',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fs_fourniseur_leads_1' => 
  array (
    'id' => '929b275f-4c8c-715b-5903-57b60d530eae',
    'relationship_name' => 'fs_fourniseur_leads_1',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'Leads',
    'rhs_table' => 'leads',
    'rhs_key' => 'id',
    'join_table' => 'fs_fourniseur_leads_1_c',
    'join_key_lhs' => 'fs_fourniseur_leads_1fs_fourniseur_ida',
    'join_key_rhs' => 'fs_fourniseur_leads_1leads_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fs_fourniseur_campaigns_1' => 
  array (
    'id' => '9368f3fe-a58f-85e0-4cea-57b60dfc2254',
    'relationship_name' => 'fs_fourniseur_campaigns_1',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'Campaigns',
    'rhs_table' => 'campaigns',
    'rhs_key' => 'id',
    'join_table' => 'fs_fourniseur_campaigns_1_c',
    'join_key_lhs' => 'fs_fourniseur_campaigns_1fs_fourniseur_ida',
    'join_key_rhs' => 'fs_fourniseur_campaigns_1campaigns_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fs_fourniseur_opportunities_1' => 
  array (
    'id' => '939b395f-babe-feb9-00f6-57b60d8cd2c1',
    'relationship_name' => 'fs_fourniseur_opportunities_1',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'Opportunities',
    'rhs_table' => 'opportunities',
    'rhs_key' => 'id',
    'join_table' => 'fs_fourniseur_opportunities_1_c',
    'join_key_lhs' => 'fs_fourniseur_opportunities_1fs_fourniseur_ida',
    'join_key_rhs' => 'fs_fourniseur_opportunities_1opportunities_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fs_fourniseur_contacts_1' => 
  array (
    'id' => '93fe24cb-654b-1080-dbc4-57b60d9cf16b',
    'relationship_name' => 'fs_fourniseur_contacts_1',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'Contacts',
    'rhs_table' => 'contacts',
    'rhs_key' => 'id',
    'join_table' => 'fs_fourniseur_contacts_1_c',
    'join_key_lhs' => 'fs_fourniseur_contacts_1fs_fourniseur_ida',
    'join_key_rhs' => 'fs_fourniseur_contacts_1contacts_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fs_fourniseur_activities_1_tasks' => 
  array (
    'id' => '969f2dbd-cf92-3bac-4439-57b60de7f6f6',
    'relationship_name' => 'fs_fourniseur_activities_1_tasks',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'fs_fourniseur',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fs_fourniseur_activities_1_calls' => 
  array (
    'id' => '973e6900-70a9-c1ad-3f49-57b60d7e8bc8',
    'relationship_name' => 'fs_fourniseur_activities_1_calls',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'fs_fourniseur',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fs_fourniseur_activities_1_meetings' => 
  array (
    'id' => '98de9d11-2412-7cc9-5d5c-57b60d7dda1a',
    'relationship_name' => 'fs_fourniseur_activities_1_meetings',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'fs_fourniseur',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fs_fourniseur_tasks_1' => 
  array (
    'rhs_label' => 'Tâches',
    'lhs_label' => 'Fournisseurs',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'fs_fourniseur',
    'rhs_module' => 'Tasks',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'fs_fourniseur_tasks_1',
  ),
);