<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/

$relationships = array (
  'fs_fourniseur_modified_user' => 
  array (
    'id' => '2960a367-6baa-86da-b3a7-57bdc0956162',
    'relationship_name' => 'fs_fourniseur_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'fs_fourniseur',
    'rhs_table' => 'fs_fourniseur',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'fs_fourniseur_created_by' => 
  array (
    'id' => '29df21a8-c0ac-0acf-396d-57bdc065c4ec',
    'relationship_name' => 'fs_fourniseur_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'fs_fourniseur',
    'rhs_table' => 'fs_fourniseur',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'fs_fourniseur_assigned_user' => 
  array (
    'id' => '2a1894dd-8917-c25d-5130-57bdc0776054',
    'relationship_name' => 'fs_fourniseur_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'fs_fourniseur',
    'rhs_table' => 'fs_fourniseur',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'fs_fourniseur_aos_contracts_1' => 
  array (
    'id' => '513f39e1-c1ab-fd06-4169-57bdc0d3c2c7',
    'relationship_name' => 'fs_fourniseur_aos_contracts_1',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'AOS_Contracts',
    'rhs_table' => 'aos_contracts',
    'rhs_key' => 'id',
    'join_table' => 'fs_fourniseur_aos_contracts_1_c',
    'join_key_lhs' => 'fs_fourniseur_aos_contracts_1fs_fourniseur_ida',
    'join_key_rhs' => 'fs_fourniseur_aos_contracts_1aos_contracts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fs_fourniseur_tasks_1' => 
  array (
    'id' => '51b8f1ce-ef8b-8f2b-d3f0-57bdc08b0726',
    'relationship_name' => 'fs_fourniseur_tasks_1',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'id',
    'join_table' => 'fs_fourniseur_tasks_1_c',
    'join_key_lhs' => 'fs_fourniseur_tasks_1fs_fourniseur_ida',
    'join_key_rhs' => 'fs_fourniseur_tasks_1tasks_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fs_fourniseur_activities_1_notes' => 
  array (
    'id' => '52b5e524-9140-9d4c-75af-57bdc063f84f',
    'relationship_name' => 'fs_fourniseur_activities_1_notes',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'fs_fourniseur',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fs_fourniseur_leads_1' => 
  array (
    'id' => '53fee8ab-05e7-15cc-1d3a-57bdc066a81c',
    'relationship_name' => 'fs_fourniseur_leads_1',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'Leads',
    'rhs_table' => 'leads',
    'rhs_key' => 'id',
    'join_table' => 'fs_fourniseur_leads_1_c',
    'join_key_lhs' => 'fs_fourniseur_leads_1fs_fourniseur_ida',
    'join_key_rhs' => 'fs_fourniseur_leads_1leads_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fs_fourniseur_campaigns_1' => 
  array (
    'id' => '54d5be3b-0cd1-7e12-c03e-57bdc00c2844',
    'relationship_name' => 'fs_fourniseur_campaigns_1',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'Campaigns',
    'rhs_table' => 'campaigns',
    'rhs_key' => 'id',
    'join_table' => 'fs_fourniseur_campaigns_1_c',
    'join_key_lhs' => 'fs_fourniseur_campaigns_1fs_fourniseur_ida',
    'join_key_rhs' => 'fs_fourniseur_campaigns_1campaigns_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fs_fourniseur_opportunities_1' => 
  array (
    'id' => '550751bd-40ad-408d-762b-57bdc0dd755f',
    'relationship_name' => 'fs_fourniseur_opportunities_1',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'Opportunities',
    'rhs_table' => 'opportunities',
    'rhs_key' => 'id',
    'join_table' => 'fs_fourniseur_opportunities_1_c',
    'join_key_lhs' => 'fs_fourniseur_opportunities_1fs_fourniseur_ida',
    'join_key_rhs' => 'fs_fourniseur_opportunities_1opportunities_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fs_fourniseur_activities_1_tasks' => 
  array (
    'id' => '58655914-7898-6b7f-26ee-57bdc0c6e811',
    'relationship_name' => 'fs_fourniseur_activities_1_tasks',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'fs_fourniseur',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fs_fourniseur_activities_1_calls' => 
  array (
    'id' => '58da3602-8f0f-99e5-c353-57bdc08e0ee9',
    'relationship_name' => 'fs_fourniseur_activities_1_calls',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'fs_fourniseur',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fs_fourniseur_activities_1_meetings' => 
  array (
    'id' => '5a7d301d-663f-47d7-1098-57bdc065354f',
    'relationship_name' => 'fs_fourniseur_activities_1_meetings',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'fs_fourniseur',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'fs_fourniseur_aos_quotes_1' => 
  array (
    'id' => '5aef7e7d-a6a6-b20b-c302-57bdc033e0db',
    'relationship_name' => 'fs_fourniseur_aos_quotes_1',
    'lhs_module' => 'fs_fourniseur',
    'lhs_table' => 'fs_fourniseur',
    'lhs_key' => 'id',
    'rhs_module' => 'AOS_Quotes',
    'rhs_table' => 'aos_quotes',
    'rhs_key' => 'id',
    'join_table' => 'fs_fourniseur_aos_quotes_1_c',
    'join_key_lhs' => 'fs_fourniseur_aos_quotes_1fs_fourniseur_ida',
    'join_key_rhs' => 'fs_fourniseur_aos_quotes_1aos_quotes_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'fs_fourniseur_contacts_1' => 
  array (
    'rhs_label' => 'Contact(s)',
    'lhs_label' => 'Fournisseurs',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'fs_fourniseur',
    'rhs_module' => 'Contacts',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'fs_fourniseur_contacts_1',
  ),
);